import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { accessCookies } from "./utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await accessCookies();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
